apiVersion: apps/v1
kind: Deployment
metadata:
  name: ak-app-deployment
  labels:
    app: ak-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ak-app
  template:
    metadata:
      labels:
        app: ak-app
    spec:
      containers:
        - name: ak-app-container
          image: 435023700720.dkr.ecr.ap-southeast-1.amazonaws.com/ak-app:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ak-app-service
spec:
  type: LoadBalancer
  selector:
    app: ak-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
